### ISSUE TITLE
Captain Commando (Japan) - Graphics are corrupted on the first boss 

### ISSUE THREAD

**Issue by sigarettenstank** [unofficial-issue-tracker/duckstation#1]
Duckstation version 0.1-5325-ga6a52b31 (master)

http://redump.org/disc/59729/

![Capture](https://user-images.githubusercontent.com/95235094/200127931-0f650802-68a1-46c8-944b-6e891eea3317.PNG)

Tested with all enhancements disabled. As you can see it's just a mess of broken pixels.

![SLPS-01567_2022-11-06_01-50-16](https://user-images.githubusercontent.com/95235094/200125794-75aa6e89-4bc0-44ec-8d0f-a528a278a4dd.png)

Here's footage of the game showing what the boss is supposed to look like. 

https://youtu.be/qOnyjLlujzc?t=115

Computer specs

![speccy](https://user-images.githubusercontent.com/95235094/200126266-7893437e-c0cc-4a81-83d0-3397cb7c0f64.PNG)

**Comment by sigarettenstank** [comment]
Still broken as of as of Duckstation 0.1-6242-gefaee4ab

**Comment by MTS2077** [comment]
It's still broken even in the latest version. (Master 889427e)

(07/16/2024)

**Comment by sigarettenstank** [comment]
Fixed
