### ISSUE TITLE
Street Fighter EX2 PLUS (japan) - The game cannot be started. no button controls at all

### ISSUE THREAD

**Issue by shobobon** [unofficial-issue-tracker/duckstation#107]
0.1-5601-g2d78b3f2 (Master)
SLPS 02508
http://redump.org/disc/12561/
![TRACK](https://i.imgur.com/zX3oXvU.jpg)

US version can be played normally.
[Legacy Build (Pre UI Update)](https://github.com/stenzek/duckstation/releases/tag/legacy) 0.1-4918-g82965f74 (dev) had no problem.
It started about a year ago.

computer spec.
![Pcspec](https://i.imgur.com/mbqY0vK.jpg)

**Comment by sigarettenstank** [comment]
@shobobon It needs digital controller. It doesn't work with analogue. Can you check if that works for you and then close this if it does?

**Comment by PowerDuckSamurai** [comment]
I can not reproduce it. Everything seems fine. 
Video: https://youtu.be/KMCB3iXqsas

latest preview build 0.1-6354-gcdea4eb6 (master)
Xbox One controller, Xinput
Windows 11

![sf](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/f99228dc-9278-4150-8c16-64862aa720d9)

**Comment by shobobon** [comment]
The US version works with an analog controller.

The Japanese version seems to require a digital controller to operate.
When I set it to the digital controller, it worked correctly.
Thank you for your verification.

![digital](https://github.com/unofficial-issue-tracker/duckstation/assets/10877297/80474f9b-2b8a-42b3-bfed-022eba66b2f1)

**Comment by PowerDuckSamurai** [comment]
@shobobon You have much easier way to switch between analog and digital controller mode. And you can do it in game : )
You just need to bind analog button in controller settings like that:

![controller](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/a4fdc1e7-791a-4244-9d01-80712f006f0b)

You can bind xbox button, just be sure that you disabled opening xbox game bar with this button. You need to set it "off" in the settings:

![button](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/3d22a891-ec31-4d55-be3f-42d6652e6c8f)

Or you can bind some button on your keyboard.

**Comment by shobobon** [comment]
@PowerDuckSamurai  Thank you for your detailed explanation of the transition from analogue to digital. :)
The issue has been resolved and this comment will be closed, thank you again.
