### ISSUE TITLE
where is located the option that allows you to press the up and down/ left and right dpad buttons at the same time?

### ISSUE THREAD

**Issue by ExGuestCJ** [unofficial-issue-tracker/duckstation#113]

**Comment by sigarettenstank** [comment]
@ExGuestCJ I don't think that option exists. You could ask on the duckstation discord.

**Comment by ExGuestCJ** [comment]
I dont have discord and im not allowed to have it

**Comment by sigarettenstank** [comment]
@ExGuestCJ Then I can't help, sorry. You can either get Discord and ask the developer or try and find his email address and ask that way. Can you close this?

**Comment by ExGuestCJ** [comment]
> @ExGuestCJ Then I can't help, sorry. You can either get Discord and ask the developer or try and find his email address and ask that way. Can you close this?

I dont have discord and im not allowed to use it. (im 14 yrs old if you ask)
