### ISSUE TITLE
Games takes much longer to boot compared to other PSX emulators

### ISSUE THREAD

**Issue by WillySteichen** [unofficial-issue-tracker/duckstation#132]
Some, like Need for Speed V-Rally, can take up to thrice as long to get to the initial loading screen after displaying the BIOS screen compared to other PSX emulators like Beetle PSX, Swanstation and PCSX, but the extended length is observable allround.

**Comment by sigarettenstank** [comment]
@WillySteichen Can you time it and post the results? This is also something it would be a good idea to check on real hardware.

**Comment by WillySteichen** [comment]
The list of approximate times in seconds is ordered from Duck, Swan, Beetle and PCSX, all with the SCPH5501 BIOS and default settings (no pre cache, seek/read timing adjustments etc.), with only fastboot enabled:
- 40 Winks: 15:39 / 12:28 / 08:83 / 09:53
- Need for Speed V-Rally: 19:53 / 09:56 / 07:89 / 06:70
- Crash Bandicoot: 16:24 / 12:28 / 10:81 /10:02
- Megaman Legends: 09:41 / 06:51 / 03:39 / 03:19
- Ridge Racer: 13:32 / 09:29 / 07:03 / 06:83
- Spyro the Dragon: 09:62 / 06:18 / 04:79 / 04:71
