### ISSUE TITLE
SLUS-00974 Medal of Honor (USA) Strange colored stars in the sky

### ISSUE THREAD

**Issue by PowerDuckSamurai** [unofficial-issue-tracker/duckstation#139]
Start the game and run the very first level. You'll see strange colored stars in the sky.
Tested with "Disable All Enhancements" option enabled. Tried Software rendering and Vulkan.

Windows 11, duckstation version - 0.1-6354-gcdea4eb6 (master)

I tried this game on original hardware and there is no such issue.

![ooh](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/d96d2366-6334-465d-b738-85217fc224d3)
![h h](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/9873e6b1-e263-49df-ae17-9e6ec7d4d6d0)

**Comment by sigarettenstank** [comment]
@PowerDuckSamurai I just checked on real hardware and the stars are meant to be that colour. It's just they're a lot less noticeable with composite video. It's very noticeable in duckstation because you're seeing the raw image with no filtering.

**Comment by PowerDuckSamurai** [comment]
@sigarettenstank Okay, thanks! : )

**Comment by PowerDuckSamurai** [comment]
It looks like it's not a bug, but a feature

**Comment by sigarettenstank** [comment]
@PowerDuckSamurai The problem is duckstation doesn't have any shader options that replicate what games look like with real hardware.

**Comment by PowerDuckSamurai** [comment]
@sigarettenstank Yeah, I had a thought that it might be because of specifics of emulation. Thank you for confirmation and explaining! : )
