### ISSUE TITLE
SLUS-00602 Newman Haas Racing (USA) The game stops itself on pause menu

### ISSUE THREAD

**Issue by PowerDuckSamurai** [unofficial-issue-tracker/duckstation#140]
Hot to reproduce:
Boot the game > Click OK, skip the qualification and start a race > During gameplay you'll see that the game stops itself on pause menu. Before that it shows fast flashing notice "Insert controller". Sometimes it happens in the beginning of the race, sometimes mid-race or in the end of it.

Tried this on 2 different PCs. And on 2 different controllers (The first one is wireless Xbox One gamepad connected with ms dongle and the second one is Xbox One gamepad too, but wired)

And no, It's not about pressing analog button. I'm not pressing it during gameplay.

Windows 11, duckstation version - 0.1-6354-gcdea4eb6 (master)
Xinput

Update. No such issue on Beetle PSX HW

![1](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/a314d3cc-1ade-40e1-aac4-9e66ae0663c1)
![2](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/0a2cd88e-0937-48c6-b322-d9961fd56bfd)
![manh](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/344d6c58-cadc-4eb6-b6ee-42392422d1f0)

**Comment by sigarettenstank** [comment]
@PowerDuckSamurai I remember there were several other games that had the same problem. I think the solution is to turn on CPU interpreter but I don't know where that option is.

**Comment by PowerDuckSamurai** [comment]
@sigarettenstank Console > Execution mode > Interpreter (Slowest)
Ok, give me a sec. I'll try in this mode too.

**Comment by PowerDuckSamurai** [comment]
@sigarettenstank Nope, it didn't help. It's the same in interpreter mode. Disconnected at the end of the race.

**Comment by sigarettenstank** [comment]
@PowerDuckSamurai Is this fixed in the latest version?

![Capture](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/353eaec5-3ece-498a-b0d6-4fe257bf75a3)

**Comment by PowerDuckSamurai** [comment]
Fixed
