### ISSUE TITLE
Rock-Climbing - Mitouhou e no Chousen - Alps-hen (Japan) - Game instantly hangs on a black screen

### ISSUE THREAD

**Issue by sigarettenstank** [unofficial-issue-tracker/duckstation#144]
Duckstation 0.1 - 6383 - gd9846093

http://redump.org/disc/24075/

![Capture2](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/8e750db1-177e-4460-92ad-23bf3af333c4)

The game doesn't boot. It instantly hangs on a black screen after the BIOS. VRAM viewer shows nothing loaded.

![SLPS-00662_2024-02-10_17-37-56](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/1168aef2-56b4-4abb-8179-eee8b3fae99d)

![Capture](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/5ae69699-567f-46cc-9e8e-5809f7f7cf52)

Computer specs

![spec](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/d9d18e1c-fdd4-49d1-bdeb-3003b104c17f)

**Comment by PowerDuckSamurai** [comment]
This game boots and plays fine if you enable 8 MB RAM.

Settings > Console > Enable 8MB RAM (Dev Console)

Thanks to mednafen's forum for this tip : ) 

![rock climbing](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/3000665a-f562-4a9e-a5e5-6241eafe7a02)
![rock climbing2](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/273d9ef6-a33e-48bd-97c2-679b5d863ee1)
![rock climbing3](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/673adfe4-0b7e-45fb-abc1-07cd6d9abf11)

**Comment by sigarettenstank** [comment]
Fixed as of Duckstation 0.1 - 7220 - g1771bfad

![Rock-Climbing - Mitouhou e no Chousen - Alps Hen (Japan) 2024-07-24-08-48-13](https://github.com/user-attachments/assets/0d134703-3c07-4555-a755-aef9036a3b23)
