### ISSUE TITLE
SLPS-00417 Racingroovy VS (Japan) It takes almost 1 minute to pass the first splash screen. 

### ISSUE THREAD

**Issue by PowerDuckSamurai** [unofficial-issue-tracker/duckstation#147]
![hash](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/8fd96849-ca21-4531-b8ca-1b0b0a8e1253)

It takes almost 1 minute to pass the first splash screen. DuckStation - 55 seconds

It takes even more time on mednafen. Mednafen - 1 minute 27 seconds

Tested with all enhancements disabled. I tried software rendering and D3D11. It's the same in interpreter and recompiler mode.

![SLPS-00417_2024-02-15_11-00-42](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/6c877d14-0f99-47cf-a3c4-162e2cf3ea73)

Additional information from the log:

![0](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/7b08fbed-39c7-424c-94c4-594436c8e615)

![01](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/05d1a858-e7a0-44d7-9636-df33e1471d2b)

![1](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/b14a98b7-e94c-4139-9d87-e0f0b6923dc6)

PC specs:
AMD Ryzen 3 2200G
16 GB RAM
AMD RX570 4GB
Windows 11
Xinput
0.1-6383-gd9846093 (master)

**Comment by sigarettenstank** [comment]
@PowerDuckSamurai That's a game bug. I tested it on real hardware a few years ago. It's because the game keeps reading the memory card over and over. Set memory card to none in duckstation if you don't want to wait.

**Comment by PowerDuckSamurai** [comment]
@sigarettenstank Got it. Thanks for reply : )
