### ISSUE TITLE
SCUS-94700 Chronicles of the Sword (USA) (Disc 1) The game doesn't boot with the default settings

### ISSUE THREAD

**Issue by PowerDuckSamurai** [unofficial-issue-tracker/duckstation#148]
The game instantly hangs on a black screen and DuckStation hangs too.

There are 2 options to fix this:

- Console > Execution mode > Interpreter (Slowest)
- If you enable "Enable Recompiler ICache" setting - the game boots and works in Recompiler mode.

PC specs:
AMD Ryzen 3 2200G
16 GB RAM
AMD RX570 4GB
Windows 11
Xinput
0.1-6392-g330397b9 (master)

![chronicles hash](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/07325107-d474-4ef5-9a7c-ae6e2420f294)

**Comment by sigarettenstank** [comment]
@PowerDuckSamurai Works fine for me with default settings. No Icache required. 

![SCUS-94700_2024-02-19_15-36-52](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/581f50f8-369e-43a9-ad8f-7d76a908fa2a)

**Comment by PowerDuckSamurai** [comment]
@sigarettenstank This is weird... Can you check your settings? Maybe you are using interpreter? And what is the version of DuckStation?

Proof: https://youtu.be/wLH7X4EguEQ

**Comment by sigarettenstank** [comment]
@PowerDuckSamurai I've never had a problem with this game. I played through it a year ago and it was fine and I've checked it again for this report and it's still fine. Maybe it's something to do with computer specs. 

![Capture](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/11bcb498-fba6-4de0-915d-94f1fd7606bb)

**Comment by PowerDuckSamurai** [comment]
@sigarettenstank 
> Maybe it's something to do with computer specs.

I checked it on my second PC with the following specs: intel core i5 11400, 16GB RAM, AMD RX6600, Windows 11
And It's the same...  https://youtu.be/4q585nSAras

Weird. I'll check tomorrow on PC with Windows 10.

**Comment by PowerDuckSamurai** [comment]
No luck on the third PC with the following specs: AMD Ryzen 5 2600, 16GB RAM, AMD RX5500XT, Windows 10

<img width="960" alt="1" src="https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/84c3512b-aec3-4fa6-a9ec-064e24652060">

No luck on the fourth PC with the following specs: Lenovo Laptop, Intel Core i5-4288U, 8GB RAM, Intel/Nvidia Graphics, Ubuntu 22.04

![2](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/176b156e-e58e-4c97-8c8a-9c3d09cb9451)

But! I decided to check android version just in case. And it boots fine...
![3](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/12b03aed-faed-49a6-b564-67040b285f2e)

**Comment by sigarettenstank** [comment]
@PowerDuckSamurai Per game settings are on by default

![Capture2](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/ed1f4451-bec6-49dd-bbe0-ed6e3758bd79)

![Capture](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/0491e830-988e-4798-9d25-31c944f1ff2c)

**Comment by sigarettenstank** [comment]
@PowerDuckSamurai 

![Capture](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/8a39b8a3-e684-42a1-beed-746fbfb7a072)

**Comment by PowerDuckSamurai** [comment]
@sigarettenstank Thanks for checking. This bug is really strange, I have no clue what is going on)

**Comment by PowerDuckSamurai** [comment]
This was fixed at some point.
