### ISSUE TITLE
Croc 2 (Europe) (Demo) Music is broken during the first loop

### ISSUE THREAD

**Issue by sigarettenstank** [unofficial-issue-tracker/duckstation#149]
Duckstation 0.1 - 6419 - g71094a0e

![Capture](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/14aefd5c-fe44-4afe-861e-9893a0c45259)

http://redump.org/disc/52140/

The level music in the Euro demo for Croc 2 is broken and extremely crackly. But only for the first loop. Once it gets to the end of the track and restarts it sounds fine. This doesn't happen in Mednafen. The full retail version also works fine.

![SLED-02119_2024-02-28_17-31-04](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/e08e7088-daa4-4575-80a1-2c3f051587b1)

[SLED-02119_2024-02-28_17-31-13.zip](https://github.com/unofficial-issue-tracker/duckstation/files/14429887/SLED-02119_2024-02-28_17-31-13.zip)

Computer specs

![Capture2](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/c7e13672-d148-4813-b1c8-5a22e495c2ce)

**Comment by PowerDuckSamurai** [comment]
Workaround to fix this: 
Settings > Console > Read Speedup > 2x (Quad Speed)

Or you can just pause and unpause the game.

**Comment by sigarettenstank** [comment]
Fixed as of Duckstation 0.1 - 7162 - g92038da3
