### ISSUE TITLE
SCUS-94426 CTR - Crash Team Racing (USA) The game crashes on boot if you use D3D11 renderer

### ISSUE THREAD

**Issue by PowerDuckSamurai** [unofficial-issue-tracker/duckstation#150]
The game crashes on boot if you use D3D11 renderer. Works fine with Vulkan or OpenGL.

Tested with all enhancements disabled. 

Probably a regression...

![crash team racing2](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/6687e707-ea79-4ff6-a0d7-09d5b0c07427)
![crash team racing1](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/c0f08da4-7447-411c-90a6-9c1e532ca267)
![crash team racing3](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/e251ecae-15f7-4c01-aee4-34ac0525fe4e)

PC specs:
AMD Ryzen 3 2200G
16 GB RAM
AMD RX570 4GB
Windows 11
Xinput
0.1-6454-g25db1633 (master)

**Comment by PowerDuckSamurai** [comment]
I guess this bug is connected to the bug in game Future Cop - L.A.P.D. (USA)

That game crashes on level called "Long Beach". It's very hard to reproduce the bug in that game (it crashes too random), but I reproduced the bug 3 or 4 times with the same D3D11 error.

![30261223](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/4ea78c37-6424-4141-9d06-502f599986b6)
![lapd1](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/40abfba3-9738-47e2-b836-088ce48c5c25)

**Comment by sigarettenstank** [comment]
@PowerDuckSamurai Is this fixed by the latest updates? 

![Capture](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/b034767a-412c-4f5e-998b-ab1ddfbd7076)

**Comment by PowerDuckSamurai** [comment]
@sigarettenstank Yes.

Fixed in 0.1-6456-gde1338cb (master).
