### ISSUE TITLE
Drag-and-drop loading of games broken on Windows

### ISSUE THREAD

**Issue by JukePlz** [unofficial-issue-tracker/duckstation#157]
A recent update has broken the drag-and-drop functionality. Other methods of loading games still work, but drag-and-drop returns this error:

![error_image](https://i.imgur.com/lKJkLNU.png)

These same files worked fine before updating, and the error is the same regardless of image type used, eg. bin+cue.

I think the commit that broke this functionality is either https://github.com/stenzek/duckstation/commit/ab445ec69d9a4169a932280aa35111e2e3e41f6e or https://github.com/stenzek/duckstation/commit/979b7bd36f0065c760a85a07a0390b0f2f69516d

**Comment by sigarettenstank** [comment]
@JukePlz Is this fixed in the latest version?
