### ISSUE TITLE
Doom (USA) (Rev 1) Textures are broken

### ISSUE THREAD

**Issue by ShagthePoker** [unofficial-issue-tracker/duckstation#160]
The intros play without issue but the game freezes on the main menu for around 30 seconds. Once the screen unfreezes, the textures are broken.  I believe this is an issue with one of the recent updates because I tested it out on version 0.1-6892 today and have had no issues. The version I used in the video below is 0.1-6922.  I've just tried out Final Doom (USA) as well and while it has a similar problem with the main menu, only the HUD is broken in-game. The rest of the textures are normal.

https://github.com/unofficial-issue-tracker/duckstation/assets/172278244/69e94829-f5e8-4f3d-a0c5-2e4c2712170d

**Comment by sigarettenstank** [comment]
@ShagthePoker Yeah it happens for me as well. Definitely broken.

![Doom (USA) 2024-06-11-09-13-44](https://github.com/unofficial-issue-tracker/duckstation/assets/95235094/31031c41-f790-4730-965f-3742123879c1)

**Comment by sigarettenstank** [comment]
@ShagthePoker Is it fixed in the latest version?

**Comment by ShagthePoker** [comment]
@sigarettenstank Nope.

**Comment by ShagthePoker** [comment]
@sigarettenstank The update released today fixed the issue.
