### ISSUE TITLE
PS2 NTSC-U bios doesn't get recognized as valid

### ISSUE THREAD

**Issue by WillySteichen** [unofficial-issue-tracker/duckstation#162]
In my case SCPH 30001 https://github.com/stenzek/duckstation/blob/master/src/core/bios.cpp#L83
Dump matches the hash, but remains invalid according to the emulator.
Wouldn't be much of a problem if not the fact fast boot doesn't work with invalid bios for whatever reason.

**Comment by yarik303** [comment]
may i ask. why u used ps2 bios?
