### ISSUE TITLE
Roswell Conspiracies - Aliens, Myths & Legends (USA) - Level music is missing and dialogue gets cut off too early 

### ISSUE THREAD

**Issue by sigarettenstank** [unofficial-issue-tracker/duckstation#57]
Duckstation 0.1 - 5410 - g1905ce3e (master) 

http://redump.org/disc/16471/

![Capture](https://user-images.githubusercontent.com/95235094/206671289-62fe42ea-998e-4c6c-8006-393cd25e3373.PNG)

Tested with all enhancements disabled. Level music is missing entirely. The opening shot of the camera panning through the level is silent. 

![SLUS-01062_2022-12-09_20-31-27](https://user-images.githubusercontent.com/95235094/206671449-c317f24f-3c03-4816-a7bb-35edcc02f8cf.png)

When you check the lock on the gate only the first word of dialogue plays before it cuts off.

[SLUS-01062_2022-12-09_20-31-55.zip](https://github.com/duckstation-unoff-issue-tracker-admin/duckstation-unofficial-issue-tracker/files/10193520/SLUS-01062_2022-12-09_20-31-55.zip)

![SLUS-01062_2022-12-09_20-32-24](https://user-images.githubusercontent.com/95235094/206671908-a67160e4-a16e-41e8-8b82-d048872bbdb1.png)

Real hardware with music playing and correct dialogue.

https://youtu.be/TLNkcKGsOKQ?t=144

Computer specs

![202328614-c2c117cb-4542-485f-8920-3b7711da8415](https://user-images.githubusercontent.com/95235094/206672117-fe13533e-c29b-4631-9f07-c542a25a66ce.PNG)

**Comment by sigarettenstank** [comment]
Both problems still happen as of Duckstation 0.1-6242-gefaee4ab

**Comment by pobgithub** [comment]
This is an issue in every PS1 emulator I've tried except mednafen

**Comment by joepogo** [comment]
Stenzek has this listed as working on his compatibility list but it's not accurate. 

He doesn't even have shockwave assault invasion earth on there or the other shockwave games. Is he even aware or even care of these issues?

As far as I know shockwave assault has always been broken in duckstation.

**Comment by sigarettenstank** [comment]
@joepogo Yeah if you check the closed issues a bunch have been fixed in the last few weeks. I don't know about any other compatibility list.

**Comment by sigarettenstank** [comment]
Fixed
