### ISSUE TITLE
Lagnacure Legend (Japan) - The game instantly crashes on a black screen

### ISSUE THREAD

**Issue by sigarettenstank** [unofficial-issue-tracker/duckstation#6]
Duckstation version 0.1-5325-ga6a52b31 (master)

http://redump.org/disc/50552/

![Capture](https://user-images.githubusercontent.com/95235094/200128705-dca9445e-ce75-4621-a088-097769194624.PNG)

All enhancements disabled. After the BIOS screen the game instantly freezes on a black screen forever. Looking at VRAM shows the game loaded a single pixel.

![SLPS-02832_2022-11-06_02-51-35](https://user-images.githubusercontent.com/95235094/200128738-fc21a24c-0738-4eb1-8bfa-0a7a4ca6c244.png)

log

![log](https://user-images.githubusercontent.com/95235094/206570965-ec6ca32f-fa05-40ef-8ebc-f86bc2bb5f7c.PNG)

It works fine in Mednafen.

![m](https://user-images.githubusercontent.com/95235094/200128750-ddb9acb2-5a06-4034-a8ca-09ee6afed639.PNG)

Computer specs

![200126266-7893437e-c0cc-4a81-83d0-3397cb7c0f64](https://user-images.githubusercontent.com/95235094/200128764-6272eccc-93a9-4f09-96db-83fe2091b55f.PNG)

**Comment by sigarettenstank** [comment]
Still doesn't boot as of Duckstation 0.1-6242-gefaee4ab

**Comment by PowerDuckSamurai** [comment]
It boots and plays fine after the latest update - 0.1-6477-g8db0fcee (master)

@sigarettenstank Do you want to check? 

![legendd](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/57b341db-6ac0-40c0-a06c-144b2d400501)
![legend](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/153a743e-9c8e-468f-b18e-3555f19b3eca)
![legend1](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/a896f079-82d0-45b2-a8a8-cb3a0be8c361)
![legend2](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/fb31447f-a4ed-45c7-aa72-14d55129d384)
![legend3](https://github.com/unofficial-issue-tracker/duckstation/assets/158706620/59a33e74-1109-409a-aef8-6fe67298df43)

**Comment by sigarettenstank** [comment]
@PowerDuckSamurai Yeah works fine now. Thanks for the tip. Now if only someone could make an English translation patch. I love that opening music by susumu hirasawa
