### ISSUE TITLE
Xenogears (USA) (Disc 2) - The game softlocks if the final boss does a specific attack 

### ISSUE THREAD

**Issue by sigarettenstank** [unofficial-issue-tracker/duckstation#83]
Duckstation 0.1 - 5437 - g06d6447e (master)

http://redump.org/disc/178/

![Capture2](https://user-images.githubusercontent.com/95235094/210188834-fe365406-4f1a-4d74-a14b-c6222b1950aa.PNG)

Tested with all enhancements disabled. The final boss of the game only has 2 attacks, one halves your health, the other one, whatever it is, causes the game to softlock. If he does this attack the game will become unresponsive. Music will continue playing but you won't be able to move or interact with the game except for the pause button. That still works for some reason. 

[Xenogears (USA) (Disc 2)_1.zip](https://github.com/duckstation-unoff-issue-tracker-admin/duckstation-unofficial-issue-tracker/files/10329758/Xenogears.USA.Disc.2._1.zip)

![SLUS-00669_2023-01-02_11-37-09](https://user-images.githubusercontent.com/95235094/210188897-6d567eb7-f41b-43df-804e-c60398c800e5.png)

![SLUS-00669_2023-01-02_11-48-09](https://user-images.githubusercontent.com/95235094/210188899-ebe66576-df02-47b7-8658-5c496b4e397d.png)

While the game is softlocked the log repeats this over and over.

![Capture](https://user-images.githubusercontent.com/95235094/210188929-05aeb622-aeac-44f0-9140-c60e513117da.PNG)

Computer specs

![210175512-770dee87-4e9f-4c48-be61-9c5952ff0a90](https://user-images.githubusercontent.com/95235094/210188908-62bd8bf7-ef64-49fc-91e9-12b714a24bb5.PNG)

**Comment by sigarettenstank** [comment]
Still broken as of Duckstation 0.1-6242-gefaee4ab

**Comment by thydungeonman** [comment]
I've heard that that softlock also happens if you play the game on ps2.

**Comment by sigarettenstank** [comment]
Fixed at some point. I did the fight 6 times and it didn't softlock.
